Repository beehive-lab/GPULlama3.java, pull requests merged in 2025-06, with the labels that each got.

#17 [model] Add support for Mistral models
  README.md
  llama-tornado
  src/main/java/com/example/LlamaApp.java
  src/main/java/com/example/Options.java
  src/main/java/com/example/aot/AOT.java
  src/main/java/com/example/auxiliary/ChatFormat.java
  src/main/java/com/example/auxiliary/LastRunMetrics.java
  src/main/java/com/example/inference/InferenceCore.java
  src/main/java/com/example/inference/InferenceEngine.java
  src/main/java/com/example/inference/engine/impl/Configuration.java
  src/main/java/com/example/inference/engine/impl/Llama.java
  src/main/java/com/example/inference/sampler/CategoricalSampler.java
  src/main/java/com/example/inference/sampler/Sampler.java
  src/main/java/com/example/inference/sampler/ToppSampler.java
  src/main/java/com/example/loader/weights/ModelLoader.java
  src/main/java/com/example/loader/weights/State.java
  src/main/java/com/example/model/Configuration.java
  src/main/java/com/example/model/Model.java
  src/main/java/com/example/model/ModelType.java
  src/main/java/com/example/model/format/ChatFormat.java
  src/main/java/com/example/model/format/LlamaChatFormat.java
  src/main/java/com/example/model/format/MistralChatFormat.java
  src/main/java/com/example/model/llama/Llama.java
  src/main/java/com/example/model/llama/LlamaConfiguration.java
  src/main/java/com/example/model/mistral/Mistral.java
  src/main/java/com/example/model/mistral/MistralConfiguration.java
  src/main/java/com/example/tokenizer/impl/LlamaTokenizer.java
  src/main/java/com/example/tokenizer/impl/MistralTokenizer.java
  src/main/java/com/example/tokenizer/impl/Tokenizer.java
  src/main/java/com/example/tokenizer/vocabulary/Vocabulary.java
  src/main/java/com/example/tornadovm/TornadoVMLayerPlanner.java
  src/main/java/com/example/tornadovm/TornadoVMMasterPlan.java
Labels: enhancement, models

#28 Add a Docker section to README with available images and usage examples
  README.md
Labels: Tooling

#32 Refactor TornadoVMMasterPlan to simplify scheduling decision for non-Nvidia HW and Mistral Models
  src/main/java/com/example/tornadovm/TornadoVMMasterPlan.java
Labels: refactoring
